# NUMPY 


In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]
arr=np.array(l)

In [3]:
type(arr)

numpy.ndarray

In [4]:
print(arr)

[1 2 3 4 5]


In [9]:
arr.shape

(5,)

In [35]:
#Multinested 

l1=[7,8,9,10,11]
l2=[5,6,7,8,9]
l3=[1,2,3,4,5]

arr=np.array([l1,l2,l3])

In [15]:
arr

array([[ 7,  8,  9, 10, 11],
       [ 5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5]])

In [16]:
arr.shape           #(3,5)first shows rows then columns.

(3, 5)

In [17]:
arr.reshape(5,3)     # reshapes the array, reshape is an inbuilt func

array([[ 7,  8,  9],
       [10, 11,  5],
       [ 6,  7,  8],
       [ 9,  1,  2],
       [ 3,  4,  5]])

In [18]:
arr.reshape(1,15)      #the size should be same when u reshape here it is 15.

array([[ 7,  8,  9, 10, 11,  5,  6,  7,  8,  9,  1,  2,  3,  4,  5]])

In [19]:
arr.reshape(4,11)

ValueError: cannot reshape array of size 15 into shape (4,11)

In [20]:
arr.reshape(2,15)

ValueError: cannot reshape array of size 15 into shape (2,15)

# INDEXING


In [32]:
#Accessing the array element 
arr1=np.array([9,8,7,6,5,4,3,2,1,0])

In [33]:
arr1[2] 

7

In [34]:
arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [36]:
arr

array([[ 7,  8,  9, 10, 11],
       [ 5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5]])

In [37]:
arr[:,:]

array([[ 7,  8,  9, 10, 11],
       [ 5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5]])

In [38]:
arr[0:2,:]         #selects two rows 0 and 1, 2 is not counted

array([[ 7,  8,  9, 10, 11],
       [ 5,  6,  7,  8,  9]])

In [39]:
arr[0:2,0:2]

array([[7, 8],
       [5, 6]])

In [42]:
arr[1:,2:4]

array([[7, 8],
       [3, 4]])

In [44]:
arr[1:2,1:4]

array([[6, 7, 8]])

In [47]:
arr=np.arange(0,10,step=2)    #step gives gap 

In [48]:
arr

array([0, 2, 4, 6, 8])

In [49]:
np.linspace(1,10,50)          #used in deep learning

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [57]:
#copy() function and broadcasting

arr[3:]=100

In [51]:
arr

array([  0,   2,   4, 100, 100])

In [58]:
arr2=arr

In [72]:
arr2[3:]=500
print(arr2)

[  0   2   4 500 500]


In [74]:
arr      #replacement of 500 has been updated n this is called as Reference time, array is a reference type 

array([   0,    2,    4, 1000, 1000])

In [75]:
arr2=arr.copy()

In [70]:
print(arr)
arr2[3:]=2000
print(arr2)

[   0    2    4 1000 1000]
[   0    2    4 2000 2000]


In [69]:
arr

array([   0,    2,    4, 1000, 1000])

In [76]:
#Some conditions very useful in Exploratory data analysis

val=2
arr<2      #only gives T/F 

array([ True, False, False, False, False])

In [77]:
arr*2      #multiplying every single element

array([   0,    4,    8, 2000, 2000])

In [78]:
arr[arr<8]   #display values less than 8 put in brackets

array([0, 2, 4])

In [79]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [80]:
#random distribution

np.random.rand(3,3)

array([[0.16512832, 0.69733126, 0.67150485],
       [0.03022406, 0.94926999, 0.69825549],
       [0.23937637, 0.7017442 , 0.51622715]])